# Since this repository belongs to a GitHub organization and Vercel doesn't provide free deployment for repository owned by organizations,
# you can deploy manually on every push or, as configured here, only when the version in package.json changes.
#
# Steps:
# 1. Install the Vercel CLI: `npm i -g vercel`
# 2. Run `vercel` and follow the prompts to set up the project.
# 3. Generate a Vercel Account Token at https://vercel.com/account/tokens.
# 4. Add the secret `VERCEL_TOKEN` to your repository.
# 5. Push a commit with a new version in package.json to trigger a deployment.

name: Vercel Deployment Workflow

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build_and_deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 2

            # Check if the version field in package.json has changed
            - name: Check version change
              id: version_check
              run: |
                  if git diff HEAD~1 HEAD -- package.json | grep -E '"version":'; then
                    echo "version_changed=true" >> $GITHUB_ENV
                  else
                    echo "version_changed=false" >> $GITHUB_ENV
                  fi

            # Exit early if no version change
            - name: Exit if no version change
              if: env.version_changed == 'false'
              run: echo "No version change detected. Skipping deployment." && exit 0

            # Install Node.js and dependencies
            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20"

            - name: Install dependencies
              run: npm install

            # Install Vercel CLI
            - name: Install Vercel CLI
              run: npm install -g vercel

            # Deploy to Vercel using CLI
            - name: Deploy to Vercel
              if: env.version_changed == 'true'
              run: vercel --token ${{ secrets.VERCEL_TOKEN }} --prod --yes

            # Output the preview URL for pull requests
            - name: Preview URL
              if: github.event_name == 'pull_request'
              run: |
                  PREVIEW_URL=$(vercel --token ${{ secrets.VERCEL_TOKEN }})
                  echo "Preview URL: $PREVIEW_URL"
